### ISSUE TITLE
关于faster_helper.py文件的问题

### ISSUE THREAD

**Issue by Zengyf-CVer** [Shudeng/GPAttack#3]
@Shudeng  @Wu-Shudeng 
你好，我运行了您的[DPAttack](https://github.com/Wu-Shudeng/DPAttack)，
执行指令：
```
python attack.py --patch_type grid --lines 3 --box_scale 1.0
python attack.py --patch_type astroid
```
发现均出现一个list格式的问题：

![ksnip_20211010-123921](https://user-images.githubusercontent.com/41098760/136682472-03d2b89f-93a5-4ac0-8266-b838f5f9eec5.png)

我查了一下，问题出现在这个函数;
https://github.com/Shudeng/GPAttack/blob/7357c610dfd6d346f8629547fa6af6fb2dbcdeb9/faster_helper.py#L120-L132

请问这个应该怎么解决？

**Comment by yihui8776** [comment]
Traceback (most recent call last):
  File "attack.py", line 281, in <module>
    success_attack = specific_attack(model_helpers, img_path, mask, save_image_dir)
  File "attack.py", line 219, in specific_attack
    res = loop.run_until_complete(asyncio.gather(*tasks))
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "attack.py", line 181, in get_attack_loss
    al, on = await helper.attack_loss(img)
  File "/workspace/faster_helper.py", line 140, in attack_loss
    scores = self.get_detector_cls_sorces(img, self.img_metas)
  File "/workspace/faster_helper.py", line 132, in get_detector_cls_sorces
    return det_scores[:, :-1] # background is the last class and exclude it
TypeError: list indices must be integers or slices, not tuple

**Comment by yihui8776** [comment]
改为  return det_scores[0][:, :-1] # background is the last class and exclude it
